# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('funding_status', models.CharField(blank=True, choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured')], default='Secured', max_length=1000, null=True)),
                ('objective', models.TextField(blank=True, default='', null=True)),
                ('level', models.CharField(blank=True, choices=[('District', 'District'), ('National', 'National')], default='District', max_length=1000, null=True)),
                ('funding_priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=1000)),
                ('verification', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('activity_cost_ugx', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_cost_usd', models.IntegerField(blank=True, default=0, null=True)),
                ('budget_assumption', models.TextField(blank=True, default='', null=True)),
                ('responsible_focal_point', models.TextField(blank=True, default='', null=True)),
                ('stackholder_focal_point', models.TextField(blank=True, default='', null=True)),
                ('time_frame', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020)),
                ('quarter', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('firstdate', models.DateField(blank=True, null=True)),
                ('lastdate', models.DateField(blank=True, null=True)),
                ('quarter_budget_usd', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Not Done', 'Not Done'), ('Ongoing', 'Ongoing')], default='Completed', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='FundingSourceOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Advocacy, Communication & Social Mobilization', max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_management.Organization'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.ManyToManyField(to='performance_management.ActivityDates'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.ManyToManyField(to='performance_management.ActivityStatus'),
        ),
        migrations.AddField(
            model_name='activity',
            name='funding_source_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_management.FundingSourceOrganization'),
        ),
        migrations.AddField(
            model_name='activity',
            name='immunization_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_management.ImmunizationComponent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_management.Organization'),
        ),
    ]
