# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_cost_ugx',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_cost_usd',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
