# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0002_auto_20200525_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
