# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-26 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0004_auto_20200525_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystatus',
            name='organization',
        ),
    ]
