# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-02 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0005_remove_activitystatus_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Not Done', 'Not Done'), ('Ongoing', 'Ongoing')], default='Complete', max_length=1000),
        ),
    ]
