# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 05:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='firstdate',
            field=models.DateField(default=datetime.datetime(2016, 5, 26, 5, 13, 37, 842000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='lastdate',
            field=models.DateField(default=datetime.datetime(2016, 5, 26, 5, 13, 46, 148000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
