# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datavalue',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='data_element',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='district',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='region',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='vaccine_category',
        ),
        migrations.AddField(
            model_name='stock',
            name='consumed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='data_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.DataElement'),
        ),
        migrations.DeleteModel(
            name='DataValue',
        ),
    ]
