# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0009_auto_20200720_1119'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='immunization_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='performance_management.ImmunizationComponent'),
        ),
    ]
