# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('name', 'cycle', 'district', 'ip', 'warehouse')]),
        ),
    ]
