# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160809_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([]),
        ),
    ]
