# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160526_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ordered',
            field=models.FloatField(default=0),
        ),
    ]
