# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160107_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='pass_count',
            field=models.IntegerField(default=0),
        ),
    ]
