# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160810_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('stock_requirement', 'month')]),
        ),
    ]
