# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160727_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='year',
            field=models.IntegerField(default=2015),
        ),
        migrations.AlterField(
            model_name='stockrequirement',
            name='year',
            field=models.IntegerField(default=2015),
        ),
    ]
