# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160810_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='planned_consumption',
            field=models.FloatField(default=0),
        ),
    ]
