# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160713_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='display_name',
            field=models.CharField(default=datetime.datetime(2016, 7, 19, 7, 13, 9, 899000, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.District'),
        ),
    ]
