# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_multipleorderfacility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='fail_count',
            new_name='default_fail_count',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='pass_count',
            new_name='default_pass_count',
        ),
        migrations.AddField(
            model_name='score',
            name='f1_fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='f1_pass_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='f2_fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='f2_pass_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='f3_fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='f3_pass_count',
            field=models.IntegerField(default=0),
        ),
    ]
