# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160310_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='access_area',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
