# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboarduser_access_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CycleFormulationScore',
        ),
    ]
