# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_district_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequirement',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
