# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_stockrequirement_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(unique=True)),
                ('category_option_combo', models.CharField(max_length=255)),
                ('attribute_option_combo', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0)),
                ('dataelement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.DataElement')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Facility')),
            ],
        ),
    ]
