# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dhis2dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhis2dataset',
            name='dataelement',
            field=models.CharField(default=datetime.datetime(2016, 9, 1, 13, 34, 39, 357733, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dhis2dataset',
            name='org_unit',
            field=models.CharField(default=datetime.datetime(2016, 9, 1, 13, 35, 49, 885195, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
