# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20160901_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhis2dataset',
            name='period',
            field=models.IntegerField(),
        ),
    ]
