# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160901_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
