# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_facility_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='type',
        ),
    ]
