# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequirement',
            name='coverage_target',
            field=models.IntegerField(default=0),
        ),
    ]
