# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_financing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('param1', models.CharField(max_length=255)),
                ('param2', models.CharField(max_length=255)),
                ('param3', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
