# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_datauploadlog_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauploadlog',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
