# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-19 12:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20171122_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='access_level',
            field=models.CharField(choices=[('Warehouse', 'Warehouse'), ('District', 'District'), ('IP', 'IP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datauploadlog',
            name='data_file',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/tmp'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1),
        ),
    ]
