# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedactivities',
            old_name='timeframe',
            new_name='Start',
        ),
        migrations.AddField(
            model_name='plannedactivities',
            name='end',
            field=models.CharField(default='Dec', max_length=200),
            preserve_default=False,
        ),
    ]
