# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20170420_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedactivities',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
