# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_auto_20170420_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedactivities',
            name='end',
        ),
        migrations.RemoveField(
            model_name='plannedactivities',
            name='start',
        ),
        migrations.AddField(
            model_name='plannedactivities',
            name='Q1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='plannedactivities',
            name='Q2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='plannedactivities',
            name='Q3',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='plannedactivities',
            name='Q4',
            field=models.NullBooleanField(),
        ),
    ]
