# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20170424_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlannedActivities',
        ),
    ]
