# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0011_delete_plannedactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('area', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('fund', models.NullBooleanField()),
                ('priority', models.CharField(max_length=200)),
                ('qtr1', models.SmallIntegerField(blank=True, default=0)),
                ('qtr2', models.SmallIntegerField(blank=True, default=0)),
                ('qtr3', models.SmallIntegerField(blank=True, default=0)),
                ('qtr4', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
