# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160315_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='data',
            new_name='content',
        ),
    ]
