# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_document_month'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
