# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160316_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, storage=home.utils.OverwriteStorage(), upload_to='documents/'),
        ),
    ]
