# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160316_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtbalance',
            name='district',
        ),
        migrations.RemoveField(
            model_name='districtbalance',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='districtbalance',
            name='district_name',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 16, 6, 18, 618030, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='districtbalance',
            name='vaccine_name',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 16, 6, 42, 413903, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, storage=home.utils.OverwriteStorage(), upload_to='./'),
        ),
    ]
