# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.CharField(max_length=200)),
                ('required', models.CharField(max_length=200)),
                ('difference', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('sub_county', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_well', models.IntegerField()),
                ('needs_maintenance', models.IntegerField()),
                ('not_working', models.IntegerField()),
                ('number_existing', models.IntegerField()),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_chain.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static', models.BooleanField()),
                ('outreach', models.BooleanField()),
                ('ficc_storage', models.BooleanField()),
                ('quarter', models.CharField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], max_length=20)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_chain.Facility')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_chain.FacilityType'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_chain.Facility'),
        ),
    ]
