# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizingfacility',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_chain.FacilityType'),
        ),
        migrations.AlterField(
            model_name='immunizingfacility',
            name='ficc_storage',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='immunizingfacility',
            name='outreach',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='immunizingfacility',
            name='static',
            field=models.NullBooleanField(),
        ),
    ]
