# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0002_auto_20200309_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblefacilitymetric',
            name='cce_coverage_rate',
            field=models.IntegerField(default=0),
        ),
    ]
