# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0002_auto_20161019_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='facility_type_id',
        ),
        migrations.AlterField(
            model_name='immunizingfacility',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cold_chain.Facility'),
        ),
    ]
