# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0003_auto_20161021_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='quarter',
            field=models.CharField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='quarter',
            field=models.CharField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], max_length=20, null=True),
        ),
    ]
