# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-31 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0004_heatreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeatReport',
            new_name='TempReport',
        ),
    ]
