# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0004_auto_20161021_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='difference',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='required',
            field=models.IntegerField(),
        ),
    ]
