# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0005_auto_20200331_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempreport',
            name='refrigerator_detail',
        ),
        migrations.AddField(
            model_name='tempreport',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
