# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0005_auto_20161022_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='actual',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='difference',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='required',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
