# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0006_auto_20161022_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='actual',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='difference',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='capacity',
            name='required',
            field=models.FloatField(),
        ),
    ]
