# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-01 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0006_auto_20200401_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempreport',
            name='balance',
        ),
    ]
