# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0007_remove_tempreport_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('funding_status', models.CharField(choices=[('Working', 'Working'), ('Not working', 'Not working'), ('Needs repair', 'Needs repair')], default='Working', max_length=20)),
                ('immunization_component', models.CharField(choices=[('Advocacy', 'Advocacy, Communication & Social Mobilization'), ('Monitoring', 'Monitoring, Supervision & Evaluation'), ('ProgrammeManagementGeneral', 'Programme Management General'), ('ProgrammeManagementFinance', 'Programme Management Finance'), ('ServiceDelivery', 'Service Delivery & Training'), ('Surveillance', 'Surveillance'), ('Vaccines', 'Vaccines, Logistics, Equipment & Infrastructure')], default='Advocacy', max_length=200)),
                ('objective', models.CharField(choices=[('Funded', 'Funded'), ('Not Funded', 'Not Funded')], default='Funded', max_length=200)),
                ('level', models.CharField(choices=[('Funded', 'Funded'), ('Not Funded', 'Not Funded')], default='Funded', max_length=200)),
                ('funding_priority_level', models.CharField(choices=[('Funded', 'Funded'), ('Not Funded', 'Not Funded')], default='Funded', max_length=200)),
                ('verification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.ManyToManyField(to='cold_chain.ActivityDates'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.ManyToManyField(to='cold_chain.ActivityStatus'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cold_chain.Organization'),
        ),
    ]
