# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0007_auto_20161022_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='old_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
