# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0008_facilitytype_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytype',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
