# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0008_auto_20200409_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Done', 'Not Done'), ('Ongoing', 'Ongoing')], default='Completed', max_length=20),
        ),
    ]
