# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0009_auto_20170209_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='old_id',
        ),
    ]
