# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0009_auto_20200409_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='funding_priority_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='level',
            field=models.CharField(choices=[('District', 'District'), ('National', 'National')], default='District', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='objective',
            field=models.CharField(max_length=300),
        ),
    ]
