# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-09 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0010_auto_20200409_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydates',
            name='date',
            field=models.DateField(),
        ),
    ]
