# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0011_auto_20200409_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='funding_status',
            field=models.CharField(choices=[('Funded', 'Funded'), ('Not Funded', 'Not Funded')], default='Funded', max_length=20),
        ),
    ]
