# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0013_facilitytype_old_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capacity',
            unique_together=set([('facility', 'quarter')]),
        ),
        migrations.AlterUniqueTogether(
            name='functionality',
            unique_together=set([('facility', 'quarter')]),
        ),
        migrations.AlterUniqueTogether(
            name='immunizingfacility',
            unique_together=set([('facility', 'quarter')]),
        ),
    ]
