# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0013_auto_20200411_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=800, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='objective',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible_focal_point',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stackholder_focal_point',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
