# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0014_auto_20200411_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='funding_priority_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='High', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='funding_status',
            field=models.CharField(choices=[('Funded', 'Funded'), ('Not Funded', 'Not Funded')], default='Funded', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='immunization_component',
            field=models.CharField(choices=[('Advocacy', 'Advocacy, Communication & Social Mobilization'), ('Monitoring', 'Monitoring, Supervision & Evaluation'), ('ProgrammeManagementGeneral', 'Programme Management General'), ('ProgrammeManagementFinance', 'Programme Management Finance'), ('ServiceDelivery', 'Service Delivery & Training'), ('Surveillance', 'Surveillance'), ('Vaccines', 'Vaccines, Logistics, Equipment & Infrastructure')], default='Advocacy', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='level',
            field=models.CharField(choices=[('District', 'District'), ('National', 'National')], default='District', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='responsible_focal_point',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stackholder_focal_point',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='verification',
            field=models.CharField(max_length=1000),
        ),
    ]
