# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0015_auto_20200411_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
