# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0017_auto_20200411_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='responsible_focal_point',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='stackholder_focal_point',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Done', 'Not Done'), ('Ongoing', 'Ongoing')], default='Completed', max_length=1000),
        ),
    ]
