# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0018_auto_20200411_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='verification',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
