# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0020_auto_20200411_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='funding_status',
            field=models.CharField(blank=True, choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured')], default='Secured', max_length=1000, null=True),
        ),
    ]
