# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-11 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0021_auto_20200411_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='immunization_component',
            field=models.CharField(blank=True, default='Advocacy', max_length=1000, null=True),
        ),
    ]
