# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-15 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0022_auto_20200411_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatus',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
