# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-23 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0023_activitystatus_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Advocacy, Communication & Social Mobilization', max_length=500, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='immunization_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_chain.ImmunizationComponent'),
        ),
    ]
