# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-23 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0024_auto_20200423_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='immunization_component',
        ),
    ]
