# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0025_remove_activity_immunization_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='immunization_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_chain.ImmunizationComponent'),
        ),
    ]
