# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0026_activity_immunization_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatus',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cold_chain.Organization'),
        ),
    ]
