# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0027_activitystatus_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatus',
            name='firstdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='lastdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
