# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-29 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0028_auto_20200424_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatus',
            name='quarter_budget_usd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
