# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0029_activitystatus_quarter_budget_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblefacilitymetric',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
