# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-25 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0030_eligiblefacilitymetric_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_status',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='immunization_component',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='activitystatus',
            name='organization',
        ),
        migrations.DeleteModel(
            name='ChangeLog',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityDates',
        ),
        migrations.DeleteModel(
            name='ActivityStatus',
        ),
        migrations.DeleteModel(
            name='ImmunizationComponent',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
