# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_chain', '0031_auto_20200525_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigeratordetail',
            name='available_net_storage_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refrigeratordetail',
            name='required_net_storage_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
